### ISSUE TITLE
FE-JS : Wallet: Support transactions to multiple recipients

### ISSUE THREAD

**Issue by AltiMario** [mlabs-haskell/TuxedoDapp#1]
Issues Fix in web-based wallet (https://github.com/Off-Narrative-Labs/Tuxedo/issues/62) The current implementation of a CLI-based wallet allows sending inputs from multiple owners in a single transaction, but it only supports a single recipient for all specified outputs.

**Comment by AltiMario** [comment]
this ticket was in our proposal, can we consider it closed? (by them or us?)

**Comment by NadigerAmit** [comment]
@AltiMario 

Blockchain-side implementation is already inplace.No restrictions for this in BC side.
This is not implemented on the CLI-wallet side. I will implement this this week.
This can be implemented in the JS wallet without dependency on CLI-wallet.

Multiple recipients and output coins need to be linked by each recipient. Struct something like the below 

struct output_per_recipients  {
pub recipient: H256,,
  pub output_amount: Vec<u128>,
}

#[derive(Debug, Args)]
pub struct SpendArgs {
    #[arg(long, short, verbatim_doc_comment, value_parser = output_ref_from_string)]
    pub input: Vec<OutputRef>,

    #[arg(long, short, verbatim_doc_comment, value_parser = h256_from_string, default_value = SHAWN_PUB_KEY)]
    pub output:Vec<output_per_recipients >,
}

**Comment by NadigerAmit** [comment]
Current situation :
Cli-Wallet implementation is pending.
Blockchain side implementation is ready.
JS Wallet can proceed with implementation.No blocking

**Comment by AltiMario** [comment]
The frontend part is missing, but having it also means changing the workflow and interface. It is not a priority for the grant scope. It can stay in the backlog until we decide to implement it as an extra feature to show the potentiality of UTXO.

**Comment by NadigerAmit** [comment]
@AltiMario - This is already implemented in the wallet side. 

Please see the implementation in 

**Implementation using Approach1 is done** : https://github.com/Off-Narrative-Labs/Tuxedo/issues/62#issuecomment-1964865040

**Test result using approach1:** https://github.com/Off-Narrative-Labs/Tuxedo/issues/62#issuecomment-1966997012

Pending item is : Update the cli-wallet README file based on the approach2.

This implementation is submitted to "webservice-with-external-signing" branch.

**Comment by JoshOrndorff** [comment]
A PR back upstream for this is welcome too if time permits :)
