### ISSUE TITLE
BlockChain - Piece: Breeding and NFT Ownership

### ISSUE THREAD

**Issue by AltiMario** [mlabs-haskell/TuxedoDapp#10]
DApp ensures NFT ownership is transferred correctly during breeding transactions. Leverage NFT attributes to determine genetics and other breeding-related factors.

**Comment by NadigerAmit** [comment]
This has 2 parts.
1. Blockchain implementation. <- This was already implemented. MLabs just implemented the refactoring w.r.t different operations. Source code for this https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wardrobe/kitties/src/lib.rs#L597-LL608
2. Wallet Implementation -> Implemented by MLabs -> https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wallet/src/kitty.rs#L433-L507

Implementaion w.r.t cli-wallet and blockchain is completed.
Now implementation in JS app is remaining.

**Comment by NadigerAmit** [comment]
Since blockchain-side implementation and Rust cli wallet is done I moving to Done as it is already submitted in the https://github.com/mlabs-haskell/Tuxedo
