### ISSUE TITLE
BlockChain - Piece:  Generating the kitty without parents

### ISSUE THREAD

**Issue by AltiMario** [mlabs-haskell/TuxedoDapp#2]
Generating the kitty without the parent when the user inserts the new key in the wallet (basically, 1 kitty is provided for free as an onboarding process).
This was in the proposal.

**Comment by NadigerAmit** [comment]
This also 2 parts ;
Implemented both in bc side and ci-wallet side as below:
Blockchain side implementation : https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wardrobe/kitties/src/lib.rs#L576-L596

Wallet side implementation : https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wallet/src/kitty.rs#L309-L356

Now JS side implementation is pending.

**Comment by NadigerAmit** [comment]
Blockchain side and cli-wallet side implementation is done.
JS side implementation is pending. No blocking.

**Comment by NadigerAmit** [comment]
Since blockchain-side implementation is done I moving to Done as it is already submitted in the https://github.com/mlabs-haskell/Tuxedo
