### ISSUE TITLE
Kitty-avatar

### ISSUE THREAD

**Issue by Winni-** [mlabs-haskell/TuxedoDapp#42]
Implement the version of random kitty avatar in ts with loading assets on demand.

**Comment by JoshOrndorff** [comment]
Shawn Tabrizi wrote a substrate kitties tutorial using Substrate and FRAME a while ago. Obviously we won't be using FRAME. He describes making a ui that renders kitties in https://www.shawntabrizi.com/substrate-collectables-workshop/#/4/rendering-kitties
