### ISSUE TITLE
CLI-Wallet: Transaction Handling

### ISSUE THREAD

**Issue by AltiMario** [mlabs-haskell/TuxedoDapp#6]
DApp implements transaction handling logic in the web application to initiate UTXO-based transactions, including NFT-related transactions, on the Tuxedo blockchain. Provide feedback to users on transaction status and confirmations.
This was in the proposal.

**Comment by NadigerAmit** [comment]
This is implemented in cli-Wallet: 
https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wallet/src/kitty.rs#L203-L205

**Comment by NadigerAmit** [comment]
If I need to implement the 2 step REST API implementation for talisman integration, I need confirmation from the @Winni- Then I will start my implementation.

**Comment by NadigerAmit** [comment]
This is done from webservice point of view.

The webservice code is submitted to https://github.com/mlabs-haskell/Tuxedo/tree/webservice-with-external-signing branch
