### ISSUE TITLE
FE-JS:Personal Dashboard

### ISSUE THREAD

**Issue by AltiMario** [mlabs-haskell/TuxedoDapp#8]
We will develop a personal dashboard for users to view and manage their NFT-based Kitties collections.
Display detailed information about each NFT, including ownership history and transaction history.
Manage NFT means, it includes below :

1. Viewing NFTs:
   Users should be able to see a comprehensive list or visual representation of all the NFTs (kitties) they own.
   Display detailed information about each NFT, including attributes such as below :
   Name
   parents(mom and dad)
   free_breedings(numbers)
   dna(H256 Hash value)
   num_breedings(number)
   Tradable(yes or No)
   Price
   Status (Ready for Raring, Tired (only for Dad), Had birth recently(only for Mom)).
2. Trade :
    Users should be able to buy the kitty from other users via the search kitty screen or directly from the Trade Kitty screen by inputting the kitty & owner details.
3. Breed :
    Users should be able to initiate breeding directly from the dashboard.
4. Update :
    Users should be able to update features such as Tradable status, price, and name from the dashboard by clicking on any cell which will navigate to update the kitty screen.
5. Interactivity:
   Make the dashboard interactive, allowing users to click on individual NFTs to access more detailed information or initiate specific actions.

**Comment by NadigerAmit** [comment]
This needs the search functionality :

Searching or showing all the kitties owned by me or any user whose key is installed in current wallet is already implemented 
https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wallet/src/main.rs#L264-L291.

And we can show all the kitties owned by all the public keys installed in the current wallet 
https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wallet/src/main.rs#L235-L263

Below is the :
https://github.com/mlabs-haskell/TuxedoDapp/issues/4

All the above features mentioned in the issue can be implemented in the JS web wallet.

**Comment by philoniare** [comment]
In terms of FE, to complete this ticket, we'll need to implement the following components from the original text:
- Trade
- Breed
- Update
