### ISSUE TITLE
BlockChain - Piece:Updating the kitty details

### ISSUE THREAD

**Issue by AltiMario** [mlabs-haskell/TuxedoDapp#9]
DApp ensures Kittie's details such as name, tradable status(Yes or No) and Price can be updated.

**Comment by NadigerAmit** [comment]
We can update mainly 2 properties of Kitty.
1. Name 
2. Price  in case of tradable kitty 

**Name update:**
This is 2 parts :
1. Blockchain side implementation: 
Name update : 
 In kitty piece <- this is the main implementation:  https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wardrobe/kitties/src/lib.rs#L609-L680

In Tradable kitty piece https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wardrobe/tradable_kitties/src/lib.rs#L429-L436: 

3. Wallet side implementation : https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wallet/src/kitty.rs#L641-L721

**Price Update:**
This is 2 parts :
1. Blockchain side implementation:
In Tradable kitty piece : https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wardrobe/tradable_kitties/src/lib.rs#L429-L438 

3. Wallet side implementation : https://github.com/mlabs-haskell/Tuxedo/blob/4caa90a2cc88b70973427c55c154f5af224118b8/wallet/src/kitty.rs#L723-L760

Both blockchain side cli-wallet side implementation is done.
Now JS implementation is pending.

**Comment by NadigerAmit** [comment]
Since blockchain-side implementation is done I moving to Done as it is already submitted in the https://github.com/mlabs-haskell/Tuxedo
